env:
  browser: true
  es6: true
parserOptions:
  ecmaVersion: 6
  sourceType: module
rules:
  array-bracket-spacing: [ warn, always ]
  arrow-spacing: warn
  brace-style: [ warn, 1tbs, { allowSingleLine: true } ]
  comma-spacing: warn
  comma-dangle: [ warn, never ]
  computed-property-spacing: [ warn, always ]
  eqeqeq: [ warn, smart ]
  func-call-spacing: [ warn, never ]
  indent: [ warn, tab, { SwitchCase: 1 } ]
  key-spacing: [ warn, { mode: minimum } ]
  keyword-spacing: warn
  linebreak-style: [ warn, unix ]
  new-parens: warn
  no-console: warn
  no-extra-semi: warn
  no-multiple-empty-lines: warn
  no-trailing-spaces: [ warn, { ignoreComments: true } ]
  no-whitespace-before-property: warn
  no-undef: error
  no-var: warn
  object-curly-spacing: [ warn, always ]
  quotes: [ warn, single ]
  semi-spacing: warn
  semi: [ warn, always ]
  space-before-function-paren: [ warn, never ]
  space-in-parens: [ warn, always, { exceptions: [ empty ] } ]
  space-infix-ops: warn